export const ErrorCodes = {
  Unauthorized: 'UNAUTHORIZED',
  Forbidden: 'FORBIDDEN',
  InvalidInput: 'INVALID_INPUT',
  InvalidBinding: 'INVALID_BINDING',
  BindingForbidden: 'BINDING_FORBIDDEN',
  BindingRevoked: 'BINDING_REVOKED',
  BindingConflict: 'BINDING_CONFLICT',
  TargetNotFound: 'TARGET_NOT_FOUND',
  TargetOffline: 'TARGET_OFFLINE',
  TargetError: 'TARGET_ERROR',
  TargetBusy: 'TARGET_BUSY',
  CapabilityUnsupported: 'CAPABILITY_UNSUPPORTED',
  LeaseConflict: 'LEASE_CONFLICT',
  LeaseRequired: 'LEASE_REQUIRED',
  LeaseExpired: 'LEASE_EXPIRED',
  DeadlineExceeded: 'DEADLINE_EXCEEDED',
  QueueCapacityExceeded: 'QUEUE_CAPACITY_EXCEEDED',
  CommandNotFound: 'COMMAND_NOT_FOUND',
  IllegalTransition: 'ILLEGAL_TRANSITION',
  UnknownOutcome: 'UNKNOWN_OUTCOME',
  PairingCodeInvalid: 'PAIRING_CODE_INVALID',
  ProtocolMismatch: 'PROTOCOL_MISMATCH',
  ExtensionAuthenticationFailed: 'EXTENSION_AUTHENTICATION_FAILED'
} as const;

export const PublicProblemCodes = [
  "INVALID_ARGUMENT",
  "CALLER_CONTEXT_UNAVAILABLE",
  "CURSOR_INVALID",
  "CURSOR_INVALIDATED_BY_OUTAGE",
  "REQUEST_NOT_FOUND",
  "REQUEST_NOT_TERMINAL",
  "REQUEST_NOT_PAUSED",
  "REQUEST_RESOLUTION_NOT_ALLOWED",
  "ENDPOINT_NOT_FOUND",
  "ENDPOINT_UNAVAILABLE",
  "ENDPOINT_KILLED",
  "ENDPOINT_NOT_KILLED",
  "INSUFFICIENT_ELIGIBLE_ENDPOINTS",
  "WINDOW_NOT_FOUND",
  "WINDOW_ENDPOINT_MISMATCH",
  "WINDOW_UNAVAILABLE",
  "WORKSPACE_NOT_FOUND",
  "WORKSPACE_NOT_OWNED",
  "WORKSPACE_UNAVAILABLE",
  "WORKSPACE_TERMINATED",
  "TAB_NOT_FOUND",
  "TAB_WORKSPACE_MISMATCH",
  "TAB_CLOSED",
  "TAB_CREATION_FAILED",
  "CDP_SESSION_NOT_FOUND",
  "CDP_SESSION_OUT_OF_SCOPE",
  "CDP_METHOD_UNSUPPORTED_BY_EXTENSION",
  "CDP_METHOD_OUTSIDE_MANAGED_TAB_SCOPE",
  "CDP_TRANSPORT_UNAVAILABLE",
  "CDP_RECONCILIATION_REQUIRES_CONFIRMATION",
  "DEBUGGER_DETACHED",
  "TAKEOVER_BINDING_MISMATCH",
  "ENDPOINT_OWNERSHIP_FROZEN",
  "CONTROL_RACE_LOST",
  "REQUEST_RESOLUTION_RACE_LOST",
  "REQUEST_INVALIDATED_BY_CONTROL",
  "TERMINATION_FAILED",
  "BROKER_NOT_READY",
  "BROKER_BUSY",
  "CURSOR_EXPIRED",
  "PAYLOAD_TOO_LARGE",
  "INTERNAL_ERROR",
  "PROFILE_FORBIDDEN",
  "PROFILE_NOT_FOUND",
  "PROFILE_QUEUE_FULL",
  "PROFILE_QUEUE_TIMEOUT",
  "PROFILE_MANAGEMENT_UNAVAILABLE",
  "PROFILE_MANAGER_STOPPING",
  "PROFILE_IN_USE",
  "PROFILE_LEASE_LOST",
  "PROFILE_INSTANCE_UNVERIFIED",
  "PROFILE_IDENTITY_MISMATCH",
  "PROFILE_HAS_ACTIVE_WORK",
  "PROFILE_START_TIMEOUT",
  "PROFILE_START_FAILED",
  "PROFILE_STOP_TIMEOUT",
  "PROFILE_EXTENSION_TIMEOUT",
  "PROFILE_EXTENSION_MISMATCH",
  "PROFILE_RUNTIME_UNSUPPORTED",
  "PROFILE_RUNTIME_INVALID",
  "PROFILE_RUNTIME_MISSING",
  "PROFILE_PATH_INVALID",
  "PROFILE_BOOTSTRAP_REQUIRED",
  "PROFILE_BOOTSTRAP_INVALID",
  "PROFILE_OPERATION_FAILED",
  "IDEMPOTENCY_CONFLICT"
] as const;

export type PublicProblemCode = (typeof PublicProblemCodes)[number];

export const PrivateTransportErrorCodes = [
  'RELAY_PROTOCOL_MISMATCH',
  'RELAY_FRAME_TOO_LARGE',
  'RELAY_MESSAGE_INVALID',
  'RELAY_CONNECTION_STALE',
  'RELAY_GENERATION_MISMATCH',
  'RELAY_ATTEMPT_NOT_FOUND',
  'RELAY_AUTHENTICATION_FAILED',
  'CAPABILITY_PROFILE_UNAVAILABLE'
] as const;

export type PrivateTransportErrorCode = (typeof PrivateTransportErrorCodes)[number];

export type ErrorCode =
  | (typeof ErrorCodes)[keyof typeof ErrorCodes]
  | PublicProblemCode
  | PrivateTransportErrorCode;

export class RelayError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly retryAfterMs?: number
  ) {
    super(message);
    this.name = 'RelayError';
  }
}
